config/routes.rb
Rails.application.routes.draw do
  #get 'user/show'
  get '/user/:id', to: 'user#show', as: 'user'



  root 'posts#index'
  # devise_for :userss
  devise_for :users, controllers: {registrations: 'registrations'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:index, :show]

  resources :posts, only: [:index, :show, :create, :destroy] do
    resources :photos, only: [:create]
    resources :likes, only: [:create, :destroy], shallow: true
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :user_id, uniqueness: {scope: :post_id}
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :post
  validates :image, presence: true
  mount_uploader :image, PhotoUploader
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :photos, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :likes, -> {order(:created_at => :desc)}
  def belongs_to? user
     Post.find_by(user_id: user.id, id: id)
  end

  def is_liked user
    Like.find_by(user_id: user.id, post_id: id)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  validates :name, presence: true
  validates :name, length: {maximum: 50}

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts, dependent: :destroy
  has_many :likes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :bio, :website])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  before_action :authenticate_user!

  def create
    @like = current_user.likes.build(like_params)
    @post = @like.post
    if @like.save
      respond_to :js
    else
      flash[:alert] = "Something went wrong ..."
    end
  end

  def destroy
    @like = Like.find(params[:id])
    @post = @like.post
    if @like.destroy
      respond_to :js
    else
      flash[:alert] = "Something went wrong ..."
    end
  end

  private
  def like_params
    params.permit :post_id
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    if !user_signed_in?
      redirect_to new_user_session_path
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_post, only: [:show, :destroy]

  def index
    @posts = Post.all.limit(10).includes(:photos, :user, :likes).order('created_at desc')
    @post = Post.new

  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      if params[:images]
        params[:images].each do |img|
          @post.photos.create(image: img[1])
        end
      end

      redirect_to posts_path
      flash[:notice] = "Saved ..."
    else
      flash[:alert] = "Something went wrong..."
      redirect_to post_path
    end
  end

  def show
    @photos = @post.photos
    @likes = @post.likes.includes(:user)
    @is_liked = @post.is_liked(current_user)
  end

  def destroy
  if @post.user == current_user
    if @post.destroy
      flash[:notice] = "Post deleted!"
    else
      flash[:alert] = "Something went wrong ..."
    end
  else
    flash[:notice] = "You don't have permission to delete this post!"
  end
    redirect_to root_path

  end

  private

  def find_post
    @post = Post.find_by id: params[:id]

    return if @post
    flash[:danger] = "Post doesn't exist!"
    redirect_to root_path

  end

  def post_params
    params.require(:post).permit :content
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  protected

  def update_resource(resource, params)
    resource.update_without_password(params)
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def show
    @user = User.find(params[:id])

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def avatar_url user
    gravatar_id = Digest::MD5::hexdigest(user.email).downcase
    "https://www.gravatar.com/avatar/#{gravatar_id}.jpg"
  end
end

app/helpers/devise_helper.rb
module DeviseHelper

  # Hacky way to translate devise error messages into devise flash error messages
  def devise_error_messages!

    return ''
  end
end

app/helpers/like_helper.rb
module LikeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Open-Insta</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
  </head>

  <body>

  <% if (current_user != nil) %>
  <%= render 'shared/navbar' %>
  <% end %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

  <div class="container">
    <%= yield %>
  </div>



  <%= render 'shared/footer' %>

  <% if flash.any? %>
    <script type="text/javascript">
        <% flash.each do |key, value| %>
        <% type = key.to_s.gsub('alert', 'error').gsub('notice', 'success') %>
        toastr.<%= type %>('<%= value %>')
        <% end %>
    </script>
  <% end %>

  </body>





</html>

app/views/likes/create.js.erb
$('#like-icon-post-<%= @post.id.to_s %>').
html('<%= link_to "Love", like_path(@like), method: :delete, remote: true, class: "core-sprite loved hide-text" %>');
$('#like-text-post-<%= @post.id.to_s %>').
html('<%= j render "posts/like_text", {likes: @post.likes} %>');
console.log("create like success");

app/views/likes/destroy.js.erb
$('#like-icon-post-<%= @post.id.to_s %>').
html('<%= link_to "Loved", post_likes_path(@post), method: :post, remote: true, class: "core-sprite love hide-text" %>');
$('#like-text-post-<%= @post.id.to_s %>').
html('<%= j render "posts/like_text", {likes: @post.likes} %>');
console.log("delete like success");

app/views/pages/home.html.erb
<%= link_to "Log out", destroy_user_session_path, method: :delete %>
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/posts/_like_icon.html.erb
<% if is_liked.present? %>
  <%= link_to "Love", like_path(is_liked),method: :delete, remote: true,
              class: "core-sprite loved hide-text"%>
<%else%>
  <%= link_to "Loved", post_likes_path(post), method: :post, remote: true,
              class: "core-sprite love hide-text"%>
<%end%>

app/views/posts/_like_text.html.erb
<% likes.each.with_index do |like, index| %>
    <strong>
    <% if likes.size == 1 %>
      <%= like.user.name %> </strong> like this
    <% elsif like == likes.last %>
      </strong>and<strong>
  <%= + like.user.name %></strong> like this
    <% elsif index > 1 %>
      </strong><%= "and " + (likes.size-index).to_s + " others " %> like this
      <% break %>
    <% elsif index==likes.size-2 || index == 1 %>
      <%= like.user.name %>
        <% else %>
      <%= like.user.name + ", " %>
    <% end %>
  <% end %>
  </strong>

app/views/posts/_photos.html.erb
<%= link_to post_path(post) do %>
<% if @post.photos.size == 1 %>
  <%= image_tag @post.photos.first.image.url(:standard), class: "card_img_top" %>
<% else %>
  <div class="carousel slide" data-ride="carousel" id="carousel-post-<%= @post.id %>">
    <div class="carousel-inner">
      <% @post.photos.each do |photo| %>
        <% if photo == @post.photos.first %>
          <div class="carousel-item active">
        <% else %>
          <div class="carousel-item">
        <% end %>
        <%= image_tag photo.image.url(:standard), class: "card_img_top" %>
        </div>
      <% end %>
      </div>
      <a class="carousel-control-prev" href="#carousel-post-<%= @post.id %>" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="carousel-control-next" href="#carousel-post-<%= @post.id %>" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>
<% end %>
<% end %>

app/views/posts/index.html.erb
<div class="d-flex flex-column align-items-center mt-3">

  <div class="col-xl-7 col-lg-8 col-md-10 col-sm-11 post-card">
    <div class="card">
      <div class="card-header">
        Create Post

      </div>
      <div class="card-body">
        <%= form_for @post, :html => {:multipart => true, :class => "dropzone upload-images p-0 border-0"} do |f| %>
          <div class="form-group row mt-2">

            <div class="col-auto pr-0">
              <%= image_tag avatar_url(current_user), class: "post-author-icon" %>
            </div>
            <div class="col pl-0">
              <%= f.text_field :content, class: "form-control border-0",
                               placeholder: "Say something about this ..." %>
            </div>
          </div>

          <div class="fallback">
            <%= file_field_tag "images[]", type: :file, multiple: true %>
          </div>
          <div class="dz-message m-0"></div>
          <div class="dropzone-previews mb-3">
            <div class="upload-photos-icon">
              <i class="fa fa-plus fa-2x" aria-hidden="true" style="color:#dddfe2"></i>
            </div>
          </div>
          <%= f.submit "Post", class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>

    <div id="post">
      <%= render 'shared/posts_list'%>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="d-flex flex-column align-items-center mt-3">
  <div class="row post box col-xl-10 col-lg-11 col-xs-12">
    <div class="col-lg-8 col-md-7 px-0 d-flex post-show-img">
      <div class="align-self-center w-100">

        <%= render "photos", {post: @post} %>

      </div>
    </div>
    <div class="col-lg-4 col-md-5 mt-sm-4 mt-md-0">
      <div class="row px-3 d-flex align-items-center">

        <%= link_to user_path(@post.user), class: "no-text-decoration" do %>
          <%= image_tag avatar_url(@post.user), class: "post-author-icon" %>

        <% end %>
        <%= link_to user_path(@post.user), class: "normal-color no-text-decoration d-flex align-self-center", title: @post.user.name do %>
          <strong><%= @post.user.name%></strong>
        <%end%>

        <%= link_to post_path(@post), method: :delete, class: "ml-auto delete-post-icon mx-0 my-auto" do %>
          <i class="far fa-trash-alt" aria-hidden="true"></i>
        <%end%>

      </div>
      <hr class="mb-0"/>
      <div class="comment-list py-2">
        <% if @post.content.present? %>
          <div>
          <span>
            <strong><%= @post.user.name%></strong>
          </span>
            <span><%= @post.content %></span>
          </div>
        <%end%>

        <!--load comment-->

        <%100.times do%>
          <div>
          <span>
            <strong>Hallo M151 Instagram</strong>
          </span>
            <span>Kommentar</span>
          </div>
        <%end%>
      </div>
      <hr class="mt-0"/>
      <div class="row actions">
        <div id="like-icon-post-<%=@post.id.to_s%>">
          <%= render "like_icon", {is_liked: @is_liked, post: @post}%>
        </div>
        <a href="#" class="core-sprite comment hide-text">Comment</a>
        <a href="#" class="core-sprite bookmark hide-text ml-auto">Bookmark</a>
      </div>
      <div id="like-text-post-<%=@post.id.to_s%>">
        <%= render "like_text", {likes: @likes}%>
      </div>

      <div class="light-color post-time"><%= time_ago_in_words(@post.created_at).upcase%>AGO</div>
      <hr/>
      <div class="row actions">
        <form action="#" class="w-100">
          <div>
            <textarea class="form-control comment-input border-0" placeholder="Add a comment ..." rows="1"></textarea>
          </div>
        </form>
      </div>

    </div>
  </div>
</div>

</div>

app/views/shared/_devisemes.html.erb
<% if resource.errors.any? %>
  <script type="text/javascript">
      <% resource.errors.full_messages.each do |c| %>
      toastr.error('<%= c %>')
      <% end %>
  </script>
<% end %>

app/views/shared/_footer.html.erb
<footer>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <button class="navbar-toggler" type="button" datatoggle="collapse" data-target="#navbar">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbar">
      <div class="navbar-nav mx-auto">
        <a href="" class="nav-item nav-link" href="#">ABOUT US</a>
        <a href="" class="nav-item nav-link" href="#">SUPPORT</a>
        <a href="" class="nav-item nav-link" href="#">BLOG</a>
        <a href="" class="nav-item nav-link" href="#">PRESS</a>
        <a href="" class="nav-item nav-link" href="#">API</a>
        <a href="" class="nav-item nav-link" href="#">JOB</a>
        <a href="" class="nav-item nav-link" href="#">PRIVACY</a>
        <a href="" class="nav-item nav-link" href="#">TERMS</a>
        <a href="" class="nav-item nav-link" href="#">DIRECTORY</a>
        <a href="" class="nav-item nav-link" href="#">LANGUAGE</a>
      </div>
    </div>
  </nav>
</footer>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light">
  <div class="container">

    <%=link_to "Icon", root_path, class: "navbar-brand core-sprite hide-text" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>


    <div class="collapse navbar-collapse" id="navbarSupportedContent">

      <%= form_tag users_path, method: :get, class: "form-inline my-2 my-lg-0 ml-md-auto", id: "users-search",
      remote: true do %>
      <%= text_field_tag :term, params[:term], class: "form-control mr-sm-2 text-center common-btn",
      placeholder: "Search", autocomplete: "off"%>
        <div id="users-result"></div>
        <% end %>
      <ul class="navbar-nav ml-md-auto">
        <li class="nav item">
          <a class="nav-link core-sprite explore-icon hide-text" href="#">Explore</a>
        </li>
        <li class="nav-item">
          <a class="nav-link core-sprite notification-icon hide-text" href="#">Notification</a>
        </li>
        <li class="nav-item">
          <%= link_to "Profile", user_path(current_user), class: "nav-link core-sprite profile-icon hide-text" %>
        </li>
      </ul>





    </div>
  </div>
</nav>

app/views/shared/_posts_list.html.erb
<%@posts.each do |post| %>
  <div class="card mt-3 post">
    <div class="card-header d-flex align-items-center">
      <%= link_to user_path(post.user), class: "no-text-decoration" do %>
        <%= image_tag avatar_url(post.user), class: "post-author-icon" %>
      <%end%>

      <%= link_to user_path(post.user), class: "normal-color no-text-decoration",
                  title: post.user.name do %>
        <strong>
          <%= post.user.name %>
        </strong>
      <% end %>
      <%= link_to post_path(post), method: :delete, class: "ml-auto delete-post-icon mx-0 my-auto" do %>
        <i class="far fa-trash-alt" aria-hidden="true"></i>
      <%end%>
    </div>

    <% if post.photos.size == 1%>
      <%= image_tag post.photos.first.image.url(:standard), class: "card_img_top" %>
    <%else %>

      <div class="carousel slide" data-ride="carousel" id="carousel-post-<%= post.id %>">
        <div class="carousel-inner">
          <%post.photos.each do |photo| %>
            <%if photo == post.photos.first %>
              <div class="carousel-item active">
            <%else %>
              <div class="carousel-item">
            <% end %>
            <%= image_tag photo.image.url(:standard), class: "card_img_top" %>
            </div>
          <% end %>
          </div>

          <a class="carousel-control-prev" href="#carousel-post-<%= post.id %>" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>

          <a class="carousel-control-next" href="#carousel-post-<%= post.id%>" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>
    <% end %>

    <div class="card-body">
      <div class="row actions">

        <div id="like-icon-post-<%= post.id.to_s %>">
          <%= render "like_icon", {is_liked: post.is_liked(current_user), post: post}%>
        </div>
        <a href="#" class="core-sprite comment hide-text"> Comment </a>
        <a href="#" class="core-sprite bookmark hide-text ml-auto"> Bookmark </a>
      </div>

      <div>
        <div id="like-text-post-<%= post.id.to_s %>">
          <%= render "like_text", {likes: post.likes}%>
        </div>
      </div>
      <div>
        <span><strong><%= post.user.name %></strong></span>
        <span>
          <%= post.content%>
        </span>
      </div>
      <%= link_to time_ago_in_words(post.created_at).upcase + " AGO",
                  post_path(post), class: "light-color post-time no-text-decoration"%>
      <hr>
      <div class="row actions">
        <form action="#" class="w-100">
          <div>
            <textarea class="form-control comment-input border-0" placeholder="Add a comment ..." rows="1"></textarea>
          </div>
        </form>
      </div>
    </div>
<%end%>

app/views/user/show.html.erb
<div class="tr">
  <div class="td"> <h3><%= @user.name %></h3> </div>
</div>

<h2></h2>

<div class="row justify-content-md-center profile-wrapper">
  <div class="col-md-4 text-center">
    <%= image_tag avatar_url(@user), width: '152', height: '152', class: "round-img" %>
  </div>
  <div class="col-md-8">
    <p class="unsername"><%= @user.name %></p>
    <% if @user == current_user %>
    <%= link_to "Edit Profile", edit_user_registration_path, class: "btn btn-outline-dark common-btn edit-profile-btn" %>
      <button type="button" class="core-sprite setting" data-toggle="modal" data-target="#exampleModal"></button>
      <% end %>


<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Settings</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>

      <div class="list-group text-center">
        <a href="#" class="list-group-item list-group-item-action">Change Password</a>
        <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "list-group-item list-group-item-action" %>
        <a href="#" class="list-group-item list-group-item-action" data-dimiss="modal">Cancel</a>
      </div>

    </div>
  </div>
</div>
  </div>
  <div class="row">
    <p class="email"><%= @user.email %></p>
  </div>


</div>